name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Test Application
    types:
      - completed

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t <dockerhub_username>/<repository_name>:latest .

    - name: Push Docker image
      run: |
        docker push <dockerhub_username>/<repository_name>:latest
